definitions:
  'taxonomy_menu__menu_link:taxonomy_menu__menu_link__categories__1':
    weight: -50
    menu_name: main
    parent: ''
    expanded: true
    enabled: true
  'taxonomy_menu__menu_link:taxonomy_menu__menu_link__categories__16':
    weight: -49
    menu_name: main
    parent: ''
    expanded: true
    enabled: true
  'taxonomy_menu__menu_link:taxonomy_menu__menu_link__categories__11':
    weight: -48
    menu_name: main
    parent: ''
    expanded: true
    enabled: true
  'taxonomy_menu__menu_link:taxonomy_menu__menu_link__categories__6':
    weight: -47
    menu_name: main
    parent: ''
    expanded: true
    enabled: true
_core:
  default_config_hash: jdY7AU0tU-QsjmiOw3W8vwpYMb-By--_MSFgbqKUTYM
