drush:
  aliases:
    remote: 'chew.${project.machine_name}.dev'
    local: 'chew.${project.machine_name}.local'

target-hooks:
    frontend-setup:
        dir: '${docroot}/themes/custom/chew'
        command: 'npm install'
    frontend-build:
        dir: '${docroot}/themes/custom/chew'
        command: 'gulp'
